name: Release tag build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment (variables, git, node, npm auth)
        uses: ./.github/workflows/prepare-environment
        with:
          npm-token: ${{ env.NPM_TOKEN }}

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Publish tag
        uses: ./.github/workflows/publish-alias-to-npm
        with:
          alias-name: ${{ env.CLEAN_SOURCE_NAME }}
          npm-repo-name: ${{ github.event.repository.name }}
          release: true
